sudo: false

language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"
  
install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_access_token
  keep-history: true
  on:
    branch: master
  local-dir: build