language: rust
cache: cargo
rust: stable
script:
  - cargo run

before_deploy:
  - echo "yongchao.li" > ./build/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_access_token
  keep-history: true
  on:
    branch: rust-build
  local-dir: build
