# Site settings
title: dodolo
email: linychuo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://linychuo.github.io" # the base hostname & protocol for your site
twitter_username: linychuo
github_username:  linychuo

# Build settings
markdown: kramdown
